default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/psf/black
    rev: 26.3.0
    hooks:
    - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        fail_fast: true
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages: [commit-msg]
        additional_dependencies: [cz-github-jira-conventional==3.0.2]
  - repo: local
    hooks:
      - id: poetry-lock
        name: poetry lock
        entry: poetry lock --no-update
        language: system
        files: ^pyproject\.toml$
        pass_filenames: false
        require_serial: true
      - id: poetry-export
        name: poetry export
        entry: bash -c 'poetry export -f requirements.txt -o requirements.txt'
        language: system
        files: ^poetry\.lock$
        pass_filenames: false
        require_serial: true
      - id: poetry-export-dev
        name: poetry export dev dependencies
        entry: bash -c 'poetry export -f requirements.txt --only dev -o requirements-dev.txt'
        language: system
        files: ^poetry\.lock$
        pass_filenames: false
        require_serial: true
